# Scaffolding generated by Casein v5.2.0.0

module Casein
  class NewsController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'News'
      @news = News.order(sort_order(:title)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View news'
      @news = News.find params[:id]
    end

    def new
      @casein_page_title = 'Add a new news'
      @news = News.new
    end

    def create
      @news = News.new news_params

      if @news.save
        flash[:notice] = 'News created'
        redirect_to casein_news_index_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new news'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update news'

      @news = News.find params[:id]

      if @news.update_attributes news_params
        flash[:notice] = 'News has been updated'
        redirect_to casein_news_index_path
      else
        flash.now[:warning] = 'There were problems when trying to update this news'
        render action: :show
      end
    end

    def destroy
      @news = News.find params[:id]

      @news.destroy
      flash[:notice] = 'News has been deleted'
      redirect_to casein_news_index_path
    end

    private

    def news_params
      params.require(:news).permit(:title, :body)
    end
  end
end
